[seeds]
    PYTHONHASHSEED = '3'
    TORCH_MANNUAL_SEED = 3
    PY_RANDOM_SEED = 3
    NP_RANDOM_SEED = 3

[filepaths]
    dataset = "../dataset/purpose_3_hop_analytics.txt"
    model_path = "../dataset/models/embedding_model"


[labels] 
    Functionality = 1
    Advertisement = 1
    Analytics = 0
    Other = 1

[dataset]
    num_paths = 100
    split_ratio = [0.8, 0.1, 0.1]
    bs = 8

[model]
    n_embed = 100
    n_hidden = 100
    n_output = 1
    n_layers = 2

[training]
    epochs = 50
    print_every = 100
    max_clip = 5
    learning_rate = 0.00001
